[mypy]
python_version = 3.11
strict = True
warn_unused_ignores = True
warn_redundant_casts = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
ignore_missing_imports = True

[mypy-rank_bm25.*]
ignore_missing_imports = True

[mypy-rank_bm25]
ignore_missing_imports = True

[mypy-sentence_transformers.*]
ignore_missing_imports = True

[mypy-sentence_transformers]
ignore_missing_imports = True

[mypy-pymupdf.*]
ignore_missing_imports = True

[mypy-fitz.*]
ignore_missing_imports = True

[mypy-bentoml.*]
ignore_missing_imports = True

[mypy-bentoml]
ignore_missing_imports = True

[mypy-sanad.corpus.pdf_extract]
disallow_untyped_calls = False

[mypy-sanad.bento_service]
disallow_untyped_decorators = False
disallow_untyped_defs = False
